# Generated by Django 6.0.2 on 2026-02-22 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0006_remove_learningobjective_is_met'),
        ('session', '0002_session_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionObjectiveProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_met', models.BooleanField(default=False)),
                ('justification', models.TextField(blank=True, help_text="The LLM's explanation for why this objective was considered met (or not).")),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_progress', to='scenarios.learningobjective')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_progress', to='session.session')),
            ],
            options={
                'verbose_name': 'session objective progress',
                'verbose_name_plural': 'session objective progress',
                'db_table': 'session_objective_progress',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'objective'), name='unique_objective_per_session')],
            },
        ),
    ]
