# Generated by Django 6.0.2 on 2026-02-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0003_sessionobjectiveprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="context_summary",
            field=models.TextField(
                blank=True,
                help_text="Cached summary of messages before the summarisation threshold.",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="summarised_up_to_sequence",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The sequence_number of the last message included in context_summary.",
                null=True,
            ),
        ),
    ]
