"""Utilities to parse raw LLM text into structured fields.

Provides helpers to extract JSON blocks and to build a ParsedLLMResponse when
possible, falling back to the raw text when needed.
"""

import json
import logging
import re
from dataclasses import dataclass, field
from .exceptions import LLMResponseParseError

logger = logging.getLogger(__name__)


@dataclass
class ParsedLLMResponse:
    """Represents the parsed response returned by a Large Language Model (LLM).

    This class is used to encapsulate and organize the various details contained
    in an LLM's response. It facilitates easy access to structured data such as
    the generated response, assessment notes, scenario status, objectives
    addressed, and the progress information.

    Attributes:
        character_response: A string containing the main response generated by
            the LLM.
        objectives_touched: A list of objectives mentioned or addressed in the
            LLM's response.
        objective_progress: A dictionary tracking the progress of various
            objectives.
        overall_progress: An integer representing the overall progress or
            evaluation status.
        scenario_state: A string describing the current state of the scenario
            as interpreted from the LLM's response.
        assessor_notes: A string containing assessor's notes or observations
            derived from the LLM's response.
    """

    character_response: str
    objectives_touched: list = field(default_factory=list)
    objective_progress: dict = field(default_factory=dict)
    overall_progress: int = 0
    scenario_state: str = ""
    assessor_notes: str = ""


class ResponseParser:
    """
    Parses raw text responses from an LLM (Language Model) into structured data.

    This class is designed to process raw text responses produced by an LLM and convert
    them into instances of the ParsedLLMResponse class. It employs a multi-strategy
    approach to parse the text, supporting direct parsing, JSON block extraction,
    and graceful degradation when structured parsing fails.

    Methods
    -------
    parse(raw_text: str) -> ParsedLLMResponse
        Attempts to parse a raw response from an LLM into a structured ParsedLLMResponse
        instance using three different strategies: direct parsing, JSON block extraction,
        and fallback to unstructured text.

    _build_from_dict(data: dict) -> ParsedLLMResponse
        Constructs a ParsedLLMResponse from a dictionary of parsed data. This internal
        method validates that the required fields are present and initializes the
        response accordingly.

    _extract_json_block(text: str) -> str | None
        Extracts a JSON block (if any) from the raw text. It supports standard markdown
        JSON blocks or manually identifies JSON-like structures within the text format.
    """

    def parse(self, raw_text: str) -> ParsedLLMResponse:
        """
        Parses a raw text response and attempts to convert it into a structured format.
        The method employs multiple strategies to parse the response, including directly
        decoding JSON, extracting and decoding potential JSON blocks wrapped in text,
        and finally falling back to a graceful degradation approach where the raw text
        is returned unparsed if all other strategies fail.

        Methods:
            parse: Attempts to parse the raw_text using various strategies to produce
                   a structured parsed LLM response.

        Parameters:
            raw_text (str): The raw text response to be parsed.

        Returns:
            ParsedLLMResponse: An object representing the structured parsing of the
            given raw text. If parsing fails, the object will include the raw text as
            its character response.
        """
        # Strategy 1: direct parse
        try:
            data = json.loads(raw_text.strip())
            return self._build_from_dict(data)
        except json.JSONDecodeError:
            pass

        # Strategy 2: extract JSON block (LLM sometimes wraps in markdown)
        json_block = self._extract_json_block(raw_text)
        if json_block:
            try:
                data = json.loads(json_block)
                return self._build_from_dict(data)
            except json.JSONDecodeError:
                pass

        # Strategy 3: graceful degradation
        logger.warning(
            "Failed to parse structured LLM response; degrading gracefully",
            extra={"raw_response_preview": raw_text[:200]},
        )
        return ParsedLLMResponse(character_response=raw_text)

    def _build_from_dict(self, data: dict) -> ParsedLLMResponse:
        """
        Parses a dictionary to construct a ParsedLLMResponse object. Ensures that the required
        field 'character_response' is present and extracts additional optional assessment
        details if available. This function serves as a utility to transform data obtained
        from an external source into a more structured format for internal usage.

        Raises:
            LLMResponseParseError: If the 'character_response' field is missing in the provided
            dictionary.

        Args:
            data (dict): Input dictionary containing the fields necessary to construct
            a ParsedLLMResponse object.

        Returns:
            ParsedLLMResponse: A structured object containing the parsed response and its
            assessment details.
        """
        if "character_response" not in data:
            raise LLMResponseParseError(
                "Response missing required 'character_response' field",
                raw_response=data,
            )
        assessment = data.get("assessment", {})
        return ParsedLLMResponse(
            character_response=data["character_response"],
            objectives_touched=assessment.get("objectives_touched", []),
            objective_progress=assessment.get("objective_progress", {}),
            overall_progress=assessment.get("overall_progress", 0),
            scenario_state=assessment.get("scenario_state", ""),
            assessor_notes=assessment.get("assessor_notes", ""),
        )

    def _extract_json_block(self, text: str) -> str | None:
        """
        Extracts a JSON block from the given text.

        This method attempts to identify and extract a block of JSON-formatted
        text from a string. It first searches for text enclosed in ```json ...
        ``` or ``` ... ```. If no such block exists, it attempts to find the
        first pair of curly braces '{' and '}' with valid positioning.

        Parameters:
        text: str
            The string from which the JSON block is to be extracted.

        Returns:
        str | None
            The extracted JSON block as a string if found, or None if no suitable
            JSON block is present in the input text.
        """
        # Match ```json ... ``` or just ``` ... ```
        pattern = r"```(?:json)?\s*([\s\S]*?)```"
        match = re.search(pattern, text)
        if match:
            return match.group(1).strip()

        # Fallback: find first { ... } block
        start = text.find("{")
        end = text.rfind("}")
        if start != -1 and end != -1 and end > start:
            return text[start : end + 1]

        return None
