# Generated by Django 6.0.2 on 2026-02-21 08:46

import core.enums
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Internal description for scenario authors. Not shown to learners.",
                    ),
                ),
                (
                    "persona",
                    models.TextField(
                        help_text="Describe the character the LLM will play. Include name, personality traits, knowledge level, emotional tendencies, and speech patterns. E.g. 'You are Dave, a 55-year-old cattle farmer from rural NSW. You speak in plain language, get anxious when the vet seems unsure, and occasionally go off on tangents about your other cattle or the weather.'"
                    ),
                ),
                (
                    "setting",
                    models.TextField(
                        help_text="Describe the physical and situational context. Where are we? What's happening? E.g. 'A remote property outside Armidale, NSW. It's a cool autumn morning. Dave called the university vet clinic because his prize Hereford isn't right.'"
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        help_text="The background knowledge the LLM character possesses — facts they know, the current state of the scenario, and any information that should drive the conversation. This is distinct from persona (who they are) and setting (where we are). E.g. symptom details, recent events, hidden information the learner needs to uncover."
                    ),
                ),
                (
                    "conversation_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Optional additional instructions for how the LLM should conduct the conversation. E.g. guidance on how forthcoming to be, whether to volunteer information or wait to be asked, emotional escalation triggers, etc.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "scenario",
                "verbose_name_plural": "scenarios",
                "db_table": "scenarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningObjective",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "NOT_STARTED"),
                            ("In Progress", "IN_PROGRESS"),
                            ("Demonstrated", "DEMONSTRATED"),
                            ("Failed", "FAILED"),
                        ],
                        db_index=True,
                        default=core.enums.StatusEnums["NOT_STARTED"],
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Short identifier. E.g. 'gather_history', 'identify_differentials'",
                        max_length=100,
                    ),
                ),
                ("key", models.SlugField(max_length=100)),
                (
                    "description",
                    models.TextField(
                        help_text="Full description of what the learner needs to demonstrate."
                    ),
                ),
                (
                    "evaluation_guide",
                    models.TextField(
                        help_text="Criteria for assessing this objective. What counts as 'touched'? What counts as 'demonstrated'? E.g. 'The learner should ask about feeding patterns, water intake, and timeline of symptom onset.'"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_objectives",
                        to="scenarios.scenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "learning objective",
                "verbose_name_plural": "learning objectives",
                "db_table": "learning_objectives",
                "ordering": ["order", "label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scenario", "key"),
                        name="unique_objective_key_per_scenario",
                    )
                ],
                "unique_together": {("scenario", "label")},
            },
        ),
    ]
