# Generated by Django 6.0.2 on 2026-02-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobjective',
            name='description',
            field=models.TextField(help_text='Description of the learning objective.'),
        ),
        migrations.AlterField(
            model_name='learningobjective',
            name='evaluation_guide',
            field=models.TextField(help_text='Criteria for evaluating whether this objective has been met.'),
        ),
        migrations.AlterField(
            model_name='learningobjective',
            name='label',
            field=models.CharField(help_text='Short identifier for the learning objective.', max_length=100),
        ),
        migrations.AlterField(
            model_name='learningobjective',
            name='status',
            field=models.CharField(choices=[('Not Started', 'NOT_STARTED'), ('In Progress', 'IN_PROGRESS'), ('Demonstrated', 'DEMONSTRATED'), ('Failed', 'FAILED')], db_index=True, default='Not Started', max_length=20),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='context',
            field=models.TextField(help_text='Background knowledge possessed by the AI character.'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='conversation_instructions',
            field=models.TextField(blank=True, help_text='Additional system instructions for conducting the conversation.'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True, help_text='Internal description for scenario authors.'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='persona',
            field=models.TextField(help_text='Description of the persona the AI should adopt.'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='setting',
            field=models.TextField(help_text='Description of the physical and situational context.'),
        ),
    ]
