# Generated by Django 6.0.2 on 2026-02-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_alter_learningobjective_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobjective',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('DEMONSTRATED', 'Demonstrated'), ('FAILED', 'Failed')], db_index=True, default='Not Started', max_length=20),
        ),
    ]
