# Generated by Django 6.0.2 on 2026-02-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0004_remove_learningobjective_evaluation_guide_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningobjective",
            name="is_met",
            field=models.BooleanField(default=False),
        ),
    ]
