# Generated by Django 6.0.2 on 2026-02-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0005_learningobjective_is_met'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningobjective',
            name='is_met',
        ),
    ]
