# Generated by Django 6.0.2 on 2026-02-22 05:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("session", "0002_session_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("SYSTEM", "system"), ("USER", "user"), ("AI", "ai")],
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("sequence_number", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("score", models.FloatField(blank=True, null=True)),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="session.session",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_number"],
                "indexes": [
                    models.Index(
                        fields=["session"], name="conversatio_session_8ae2ff_idx"
                    ),
                    models.Index(fields=["role"], name="conversatio_role_d0918c_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "sequence_number"),
                        name="unique_sequence_per_session",
                    )
                ],
            },
        ),
    ]
