# Generated by Django 6.0.2 on 2026-02-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="role",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "system"),
                    ("USER", "user"),
                    ("ASSISTANT", "assistant"),
                ],
                max_length=20,
            ),
        ),
    ]
